// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzwbejdPJMKPtQpTjkSfYU2tJaccEOUbk',
    appId: '1:1019073688436:web:5262795d97ad56f9523221',
    messagingSenderId: '1019073688436',
    projectId: 'nisan-photo-app',
    authDomain: 'nisan-photo-app.firebaseapp.com',
    storageBucket: 'nisan-photo-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP5vd9e9v7tbZw9l-gf0Suxi6afRN_IYg',
    appId: '1:1019073688436:android:da7a61d7be1561a1523221',
    messagingSenderId: '1019073688436',
    projectId: 'nisan-photo-app',
    storageBucket: 'nisan-photo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGDFqOJRaudvzIglP5zBLX7PuCivQt3Po',
    appId: '1:1019073688436:ios:61a7d66c4313637e523221',
    messagingSenderId: '1019073688436',
    projectId: 'nisan-photo-app',
    storageBucket: 'nisan-photo-app.appspot.com',
    iosBundleId: 'com.example.nisanPhotoApp',
  );

}